Implement flow algorithm
TeamGraphix/fastflow pull request #3
Opened 2024-06-20 03:59 UTC by EarlMilktea

Resolves #2 .

2024-06-21 21:12 UTC, EarlMilktea commented
@shinich1 Implemented gflow.

## Tasks

- [ ] Add Python tests
- [ ] Setup CI (Python + Rust)
- [ ] Add comments
- [ ] Setup docs
- [ ] Benchmark

2024-06-22 19:50 UTC, EarlMilktea commented
# ⚡ Benchmarking

Find the gflow of...

- `i`-qubit random QC
- Of depth `i`
- 100 samples/entry

⚠ May contain errors.

## `graphix.gflow.find_gflow`

| `i` | time (ms)          | stderr (ms)        |
| --- | ------------------ | ------------------ |
| 2   | 19.009382470000002 | 0.6628736280631469 |
| 3   | 75.83718989        | 2.063014687241483  |
| 4   | 383.36668434       | 10.12828169055268  |

## `fastflow.gflow.find`

| `i` | time (ms)           | stderr (ms)           |
| --- | ------------------- | --------------------- |
| 2   | 0.05443114          | 0.0009230501164097214 |
| 3   | 0.11776354          | 0.00151554304257055   |
| 4   | 0.21261396000000002 | 0.0031804414167508253 |
| 5   | 0.40694433999999996 | 0.0062023435879870435 |
| 6   | 0.74527974          | 0.010543919371871354  |
| 7   | 1.2411830700000002  | 0.01595712269075008   |
| 8   | 2.38443002          | 0.029252221929979876  |
| 9   | 3.76497817          | 0.04407250301182826   |
| 10  | 5.623669900000001   | 0.05823929324986268   |
| 11  | 7.714499050000001   | 0.3886029278762744    |
| 12  | 10.62514183         | 0.12914857202007932   |
| 13  | 16.02541883         | 0.5546017061202904    |
| 14  | 23.145998489999997  | 0.24453927551541105   |
| 15  | 32.648691490000004  | 0.27614325883549373   |
| 16  | 39.654400270000004  | 0.7271256818307451    |
| 17  | 55.18222284         | 1.0060489308203906    |
| 18  | 71.53060902         | 1.175167722075936     |
| 19  | 95.57744375         | 1.1030700519139047    |
| 20  | 111.74057805999999  | 1.3985659519354365    |

2024-06-25 19:01 UTC, EarlMilktea commented
Try it locally:
[bench.zip](https://github.com/user-attachments/files/15976511/bench.zip)

2024-07-14 07:45 UTC, shinich1 commented on python/fastflow/flow.py
> +def find(g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V]) -> FlowResult[V] | None:
unless you have specific reason for `find`, how about using `find_flow`, `find_gflow`, `find_pauliflow` as in original package?

2024-07-14 11:58 UTC, shinich1 commented on tests/test_gflow.py
> +    assert result == c.gflow
nice that the results now agree/is consistent with graphix implementation, e.g. this test. 
@EarlMilktea shall we merge this and start new one for better documentations / packaging / etc?
If we're going for merge, I would like to ask @thierry-martinez to take a look too.

2024-07-14 12:20 UTC, shinich1 commented on python/fastflow/pflow.py
> +    g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V], pplane: Mapping[V, PauliPlane] | None = None
note: argument `plane` is `PauliPlane` for pauliflow, not plane + angle as in original impl. Seems like a natural way as an independent package. we just need to different conversions for pauliflow finding (incl `X` plane, for example) if starting with a pattern

2024-07-14 12:48 UTC, EarlMilktea commented on python/fastflow/flow.py
> +def find(g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V]) -> FlowResult[V] | None:
I personally don't prefer the naming `find_XXX` for the reasons below:

- `find` is redundant: it's obvious that the function somehow finds `XXX`
- The APIs are different, so there's no good reason to adopt consistent namings (or even confusing)

2024-07-14 12:52 UTC, EarlMilktea commented on tests/test_gflow.py
> +    assert result == c.gflow
@shinich1 For the Pauli flow, my impl. is slightly different from graphix.

2024-07-14 12:55 UTC, EarlMilktea commented on python/fastflow/pflow.py
> +    g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V], pplane: Mapping[V, PauliPlane] | None = None
I adopted this API to ensure that users are absolutely sure that the nodes are Pauli. The current impl. of `graphix.gflow` is prone to floating-point rounding errors.

2024-07-14 13:01 UTC, shinich1 commented on python/fastflow/pflow.py
> +    g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V], pplane: Mapping[V, PauliPlane] | None = None
Yes I found this impl safer. It's worth thinking how to incorporate similar structure to graphix package (will open issue)

2024-07-14 13:03 UTC, shinich1 commented on tests/test_gflow.py
> +    assert result == c.gflow
@EarlMilktea thought it was still consistent with the definition and is max-delayed?

2024-07-14 13:08 UTC, shinich1 commented on python/fastflow/flow.py
> +def find(g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V]) -> FlowResult[V] | None:
sure

2024-07-14 13:20 UTC, EarlMilktea commented on tests/test_gflow.py
> +    assert result == c.gflow
Yes. Maybe needs discussion before merge.

2024-07-29 06:47 UTC, EarlMilktea commented
@thierry-martinez Could you review this PR?

2024-07-30 23:53 UTC, thierry-martinez requested changes
Good work, and sorry for the delay. I didn't understand everything yet, but I post a first batch of comments for now.

2024-07-30 23:53 UTC, thierry-martinez commented on src/internal/test_utils.rs
> +}
`graph` could be define as a usual function: 
```suggestion
fn graph<const N: usize>(adj: &[(usize, usize); N]) -> Graph {
    match adj.iter().map(|(u, v)| [u, v].into_iter()).flatten().max() {
        None => vec![],
        Some(n) => {
            let mut g = vec![Nodes::new(); n + 1];
            for &(u, v) in adj {
                g[u].insert(v);
                g[v].insert(u);
            };
            g
        }
    }
}
```

2024-07-30 23:53 UTC, thierry-martinez commented on src/flow.rs
> +        cset.union_with(oset_work.intersection(&icset));
If I understand correctly, `union_with` is just `extend`.

```suggestion
        oset.extend(&oset_work);
        cset.difference_with(&cset_work);
        cset.extend(oset_work.intersection(&icset));
```

2024-08-02 13:17 UTC, EarlMilktea commented on python/fastflow/gflow.py
> +        f[i2v[i]] = si_
None in particular.

2024-08-02 13:38 UTC, EarlMilktea commented on src/flow.rs
> +        cset.union_with(oset_work.intersection(&icset));
I'm using the name `union_with` to clarify what I definitely want to do.

2024-08-02 14:20 UTC, EarlMilktea commented on python/fastflow/flow.py
> +    return flow.find(g, iset, oset)
I intentionally added Python-side validation to make room for error message customization.

2024-08-02 15:10 UTC, EarlMilktea commented on src/gflow.rs
> +}
I gave up doing so because there seems to be no rigid way to declare that there is `enum` defined somewhere else.

2024-08-02 15:15 UTC, EarlMilktea commented on src/internal/validate.rs
> +}
These two properties are automatically satisfied be it correct or not, as my impl. first fills `layer` with zeros.

2024-08-02 15:20 UTC, EarlMilktea commented on src/pflow.rs
> +            }
Definitely true...
Do you have any good ideas?

2024-08-02 15:27 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +        }
I intentionally didn't use this kind of simplification too much, because I'm not sure TeamGraphix can maintain it in the future...

2024-08-02 22:37 UTC, thierry-martinez commented on src/flow.rs
> +        cset.union_with(oset_work.intersection(&icset));
I would prefer to use standard names whenever possible. Moreover, the implementation of union_with is not just an alias for extend; it contains clone operations that we usually want to eliminate when possible in Rust.

2024-08-02 22:40 UTC, thierry-martinez commented on src/internal/gf2_linalg.rs
> +        }
I tend to think that the simpler the code is, the more maintainable it is. In particular, in this code, the trick of using `with_capacity` is not crystal clear and forces you to repeat the length twice. On the other hand, building data structures in Rust by collecting iterators is idiomatic.

2024-08-02 22:49 UTC, thierry-martinez commented on python/fastflow/flow.py
> +    return flow.find(g, iset, oset)
I propose waiting for the need for such customization before adding pydantic validation. It is not clear to me that this is something we would want to do with pydantic (considering the cost of performing validation twice), or if we would prefer to handle this directly in Rust.

2024-08-03 02:25 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +        }
I see.

It would be acceptable if you're willing to help me maintain this pkg.

2024-08-03 02:59 UTC, EarlMilktea commented on src/internal/test_utils.rs
> +}
Merged in 77a4602526fa0d77420ca72bcca44c757d5113ce.

2024-08-03 02:59 UTC, EarlMilktea commented on src/internal/test_utils.rs
> +}
Merged in 77a4602526fa0d77420ca72bcca44c757d5113ce.

2024-08-03 03:04 UTC, EarlMilktea commented on src/pflow.rs
> +    let yzset = matching_nodes!(pplanes, PPlane::Y | PPlane::Z);
I would prefer to initialize the three independently, as they're independent and this part is unlikely to be a bottleneck.
Let me suggest `fn`-based refactor.

2024-08-03 03:16 UTC, EarlMilktea commented on src/pflow.rs
> +    let yzset = matching_nodes!(pplanes, PPlane::Y | PPlane::Z);
Please see 33d4ddf3289c3aeb54bcb8ef59142dbf6a799571.

2024-08-03 03:17 UTC, EarlMilktea commented on python/fastflow/gflow.py
> +        f[i2v[i]] = si_
Fixed in c31ee5e8ad69f9363b4dc08b355671c54ca48d14.

2024-08-03 03:25 UTC, EarlMilktea commented on python/fastflow/flow.py
> +    return flow.find(g, iset, oset)
Fixed in d7d5ed0a79f4fd55b857656fdd3d147ff0715225.

2024-08-03 03:34 UTC, EarlMilktea commented on src/flow.rs
> +        cset.union_with(oset_work.intersection(&icset));
Fixed in 1166afde2d094c116bcdd982196b5c38921e65e2.

2024-08-03 04:20 UTC, EarlMilktea commented on src/pflow.rs
> +        .collect::<hashbrown::HashMap<_, _>>();
Fixed in 5486cdce33fb6f451d06ea92d96ad8b345318a46.

2024-08-03 06:07 UTC, EarlMilktea commented on python/fastflow/flow.py
> +    oset_ = {v2i[v] for v in oset}
Fixed in dd64a62e1df9af84466854700c3ec20ed51c2a33.

2024-08-03 06:29 UTC, shinich1 commented on src/internal/gf2_linalg.rs
> +        }
To me, initial version is easier to understand hence maintain. `with_capacity` does not look too tricky?

2024-08-03 07:04 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +    work: GF2Matrix,
Fixed in deaf89160f0df49b43542889d5209094d5eaef7b.

2024-08-03 07:13 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +        }
@shinich1

@thierry-martinez 's suggestion is actually very idiomatic for Rustaceans, even though it looks quite weird for outsiders...

So as long as @thierry-martinez (or other contributors being fluent in Rust) can help us it's not a problem, or even preferable.

2024-08-03 07:22 UTC, EarlMilktea commented on src/internal/validate.rs
> +    Ok(())
Merged in 64c174ced8ed6019ada30d96ec8aabae1730a5bd.

2024-08-03 07:59 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +            if self.work[i][c] {
Fixed in f6794f844b7b42bd4a103809bd555f31f9e87ab7.

2024-08-03 07:59 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +        for i in rank..self.rows {
Fixed in f6794f844b7b42bd4a103809bd555f31f9e87ab7.

2024-08-03 08:50 UTC, EarlMilktea commented on src/pflow.rs
> +            }
Resolved in 3bd4f5096ddfa3f9d43af37507b69b8578677884.

2024-08-03 09:14 UTC, EarlMilktea commented
@shinich1 @thierry-martinez 

Resolved the comments except for Rust-specific idioms.
How should I do for that?

2024-08-03 11:36 UTC, thierry-martinez approved these changes
I just added a minor comment to remove a lookup while iterating over a map, and a suggestion for exporting Rust enums in Python. I agree to merge this PR with or without these suggestions being taken into account!

2024-08-03 11:36 UTC, thierry-martinez commented on src/gflow.rs
> +}
I tried to use `pyclass` here. I think it is reasonable to repeat the enum in `.pyi` for the Python typer to know the variants of the enum. https://github.com/TeamGraphix/fastflow/compare/2-implement-flow-algorithm...thierry-martinez:fastflow:2-implement-flow-algorithm

2024-08-03 11:36 UTC, thierry-martinez commented on src/internal/gf2_linalg.rs
> +        }
It is not worth bike-shedding on this. I hope I will be able to help maintain this package in the long term, but we can keep the `for-loop` code here if you prefer!

2024-08-03 12:36 UTC, shinich1 approved these changes
Thanks @EarlMilktea! Please update the `ZX` plane name to `XZ` to be consistent with `graphix.plane.Plane` notation. Otherwise I am happy for this to be merged as a first version. 
I have not fully gone through the every details of the code, will continue to do so and will write issues when I have questions/problems.

Please also publish first version on `pypi`, it's good to get ahold of the name before its taken.

2024-08-03 12:36 UTC, shinich1 commented on python/fastflow/common.py
> +    """MBQC flow.
```suggestion
    """Causal flow [Danos and Kashefi, Phys. Rev. A 74, 052310] of an open graph. 
```

2024-08-03 12:36 UTC, shinich1 commented on python/fastflow/common.py
> +    """MBQC gflow.
```suggestion
    """Generalized flow [Browne et al., NJP 9,  250 (2007)] of an open graph.
```

2024-08-03 12:36 UTC, shinich1 commented on python/fastflow/gflow.py
> +See Mhalla et al. (2008) for more details.
```suggestion
See [Mhalla and Perdrix, Proc. of 35th ICALP, 857 (2008)] and [Backens et al., Quantum 5, 421 (2021)] for more details.
```

2024-08-03 12:36 UTC, shinich1 commented on python/fastflow/common.py
> +    ZX = 2
```suggestion
    XZ = 2
```
We define `XZ` not `ZX` planes (see `graphix.pauli.Plane`). I think it's best to have the same notations

2024-08-03 12:36 UTC, shinich1 commented on python/fastflow/flow.py
> +See Mhalla et al. (2008) for more details.
```suggestion
See [Mhalla and Perdrix, Proc. of 35th ICALP, 857 (2008)] for more details.
```

2024-08-03 12:36 UTC, shinich1 commented on src/gflow.rs
> +                    "must satisfy ({i} in f({i}), {i} in Odd(f({i})) = (true, true): ZX"
```suggestion
            Plane::XZ if in_info != (true, true) => {
                let err = anyhow::anyhow!("plane check failed").context(format!(
                    "must satisfy ({i} in f({i}), {i} in Odd(f({i})) = (true, true): XZ"
```

2024-08-03 12:36 UTC, shinich1 commented on src/gflow.rs
> +        if let Plane::XY | Plane::ZX = planes[&u] {
```suggestion
        if let Plane::XY | Plane::XZ = planes[&u] {
```

2024-08-03 12:36 UTC, shinich1 commented on src/gflow.rs
> +///   - `2`: ZX
```suggestion
///   - `2`: XZ
```

2024-08-03 12:36 UTC, shinich1 commented on src/gflow.rs
> +            if let Plane::YZ | Plane::ZX = planes[&u] {
```suggestion
            if let Plane::YZ | Plane::XZ = planes[&u] {
```

2024-08-03 12:36 UTC, shinich1 commented on pyproject.toml
> +# Must be consistent with Cargo.toml
how about adding `authors` and `maintainers` fields and populate with @EarlMilktea ?
also `readme`, `license`, `description` and `classifiers` which will be used on `pypi` page afaik

2024-08-03 12:36 UTC, shinich1 commented on src/flow.rs
> +        // if cfg!(debug_assertions) {
will this be uncommented?

2024-08-03 16:27 UTC, EarlMilktea commented on src/gflow.rs
> +}
This worked like a charm only with trivial fixes! Let me adopt it.

2024-08-03 16:36 UTC, EarlMilktea commented
@shinich1 
For me, it is more preferable to use `ZX` to make definition consistent with $\mathbb{Z}_3$, i.e., planes can be written as `i (i + 1) % 3` where `X = 0`, `Y = 1`, and `Z = 2`.
This is also intuitive for us familiar with right-hand rule and compatible with vector cross product.
Is there any good reason to use `XZ`? If none, shouldn't we use `ZX`?

2024-08-03 16:40 UTC, EarlMilktea commented on src/flow.rs
> +        // if cfg!(debug_assertions) {
In the future, but not now. This code would help us with debugging...

2024-08-03 16:42 UTC, EarlMilktea commented on python/fastflow/common.py
> +    ZX = 2
Please see here: https://github.com/TeamGraphix/fastflow/pull/3#issuecomment-2266979399. I intentionally changed the definition.

2024-08-03 17:46 UTC, EarlMilktea commented on src/gflow.rs
> +        let fi = &f[&i];
Fixed in ae93642954aa753b8a140baa5e778d5e10267929.

2024-08-03 17:49 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +                if self.work[r][c] {
Fixed in 1813d73f636f27b1af2efce01ebce1fae20006cf.

2024-08-03 17:49 UTC, EarlMilktea commented on src/internal/gf2_linalg.rs
> +            if self.work[i].count_ones(..self.cols) != 0 {
Fixed in 1813d73f636f27b1af2efce01ebce1fae20006cf.

2024-08-03 18:25 UTC, EarlMilktea commented on src/gflow.rs
> +}
Merged in 5375959b30bea3151d6289348a9e210546080c8e.

2024-08-03 19:18 UTC, EarlMilktea commented on python/fastflow/common.py
> +    """Check if g is a valid MBQC graph.
Merged in 6d8d943a3cd19bb5089653b83c93ae8aa73d5068.

2024-08-04 00:19 UTC, shinich1 commented
> @shinich1 
> 
> For me, it is more preferable to use `ZX` to make definition consistent with $\mathbb{Z}_3$, i.e., planes can be written as `i (i + 1) % 3` where `X = 0`, `Y = 1`, and `Z = 2`.
> 
> This is also intuitive for us familiar with right-hand rule and compatible with vector cross product.
> 
> Is there any good reason to use `XZ`? If none, shouldn't we use `ZX` or support both?

It is the notation used in 'there and back again' and other related MBQC literatures. I understand your intuition though.

2024-08-05 01:12 UTC, EarlMilktea commented on src/gflow.rs
> +            if let Plane::YZ | Plane::ZX = planes[&u] {
Resolved in 3e36c72391b760c331fe32121aed703ab1b3a4d6.

2024-08-05 01:12 UTC, EarlMilktea commented on src/gflow.rs
> +///   - `2`: ZX
Fixed in 3e36c72391b760c331fe32121aed703ab1b3a4d6.

2024-08-05 01:12 UTC, EarlMilktea commented on src/gflow.rs
> +        if let Plane::XY | Plane::ZX = planes[&u] {
Fixed in 3e36c72391b760c331fe32121aed703ab1b3a4d6.

2024-08-05 01:13 UTC, EarlMilktea commented on python/fastflow/common.py
> +    ZX = 2
Fixed in 3e36c72391b760c331fe32121aed703ab1b3a4d6.

2024-08-05 01:47 UTC, EarlMilktea commented on pyproject.toml
> +# Must be consistent with Cargo.toml
Resolved in aba20b9c8778b963aec130784234799c86b20365 and 2037ec0ba92699dbf533a14993f03ae05eb6966d.

@thierry-martinez I added you to the maintainers. Thank you for your valuable suggestions!

2024-08-08 14:12 UTC, shinich1 commented
@EarlMilktea great work, please squash and merge.

2024-08-08 14:18 UTC, merged