Finalize package
TeamGraphix/fastflow pull request #6
Opened 2024-08-15 05:29 UTC by EarlMilktea

## Tasks

- [ ] Setup Python doc
- [ ] Setup Rust doc
- [ ] Setup `twine`
- [ ] Upload to PyPI

2024-08-16 05:34 UTC, shinich1 commented
@EarlMilktea great, I suggest showing benchmarking on readme. e.g. https://github.com/qulacs/qulacs

2024-08-16 06:47 UTC, EarlMilktea commented
@shinich1 @masa10-f 

Do you have good ideas on how we should choose the graphs to try?

2024-08-16 07:38 UTC, masa10-f commented
I don't have a satisfactory answer, but we usually benchmark for a graph directly transpiled from circuit and its Pauli-processed one.

2024-08-17 03:17 UTC, shinich1 commented
note: perhaps add this kind of notes to all python files in the package, and maybe similar manner to rust files?
```python
#!/usr/bin/env python3
# This code is part of github.com/TeamGraphix/fastflow.
#
# (C) Copyright teamgraphix 2024
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.
```

2024-08-19 18:10 UTC, EarlMilktea commented
> #!/usr/bin/env python3

Shebang is unnecessary as `.py` files are not executable (no `x` permissions).

2024-08-20 07:21 UTC, shinich1 commented
The point is that we be explicit about our license terms on every source file, to deter use outside terms. do remove the shebang

2025-01-25 15:02 UTC, EarlMilktea commented
@shinich1 Maybe later. Currently I'm not planning to do that immediately.

2025-04-15 04:22 UTC, shinich1 approved these changes

2025-04-15 23:19 UTC, shinich1 commented
@thierry-martinez could you take a look at this?

2025-04-24 16:15 UTC, thierry-martinez requested changes
Some comments, mainly on error management.

2025-04-24 16:15 UTC, thierry-martinez commented on python/fastflow/_common.py
>          g_: list[set[int]] = [set() for _ in range(n)]
Note that indices of `g_` should match the indices of `self.__v2i`.
I propose the following implementation:
```python
    return [self.encode_set(g[v].keys()) for v in self.__i2v]
```

2025-04-24 16:15 UTC, thierry-martinez commented on src/common.rs
> +pub enum FlowValidationError {
You can annotate with
```rust
#[pyclass]
```
and then expose the class to Python with
```rust
m.add_class::<common::FlowValidationError>()?;
```

2025-04-24 16:15 UTC, thierry-martinez commented on src/internal/validate.rs
> +                let err = anyhow::Error::from(ExcessiveNonZeroLayer(u));
It would be more precise to have the return type `Result<(), FlowValidationError>` and not to use `anyhow` encapsulation here, since we don't need to mix with other error types at this point. We would then be able to report the `FlowValidationError` directly to Python.

2025-04-24 16:15 UTC, thierry-martinez commented on src/pflow.rs
> +    }
```suggestion
    validate::check_domain(f_flatiter, &vset, &iset, &oset).map_err(PyValueError::new_err)?;
```

2025-04-24 17:32 UTC, EarlMilktea commented on python/fastflow/_common.py
>  def check_graph(g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V]) -> None:
> The `TypeError` cases should be caught statically by the type checker

That's definitely true but I added them for safety. Should I totally remove them for simplicity?

> `any(True for _ in nx.selfloop_edges(g))`

Looks good. Let me use it!

> Instead of defining `msg` before raising the exception, inline the message directly in the `ValueError`

This is based on https://docs.astral.sh/ruff/rules/raw-string-in-exception/ and I don't want to fix. I admit this rule itself is very controversial and is actually not included in the new `graphix` linter rulesets.

2025-04-24 17:44 UTC, EarlMilktea commented on python/fastflow/_common.py
>  def check_graph(g: nx.Graph[V], iset: AbstractSet[V], oset: AbstractSet[V]) -> None:
Second one is merged in 3daa659ab35ca1a27f3ebaf3b8d074a87ad52742 .

2025-04-24 17:44 UTC, EarlMilktea commented on python/fastflow/_common.py
>          raise ValueError(msg)
Merged in accb24cac07a5bd65ef2c297dc770f6045e6dd11 .

2025-04-24 17:52 UTC, EarlMilktea commented on python/fastflow/_common.py
> +        return type(err)(self.decode_errmsg(str(err)))
Definitely true. Let me redesign the error reporting facilities.

2025-04-24 18:09 UTC, EarlMilktea commented on src/gflow.rs
>  pub fn find(g: Graph, iset: Nodes, oset: Nodes, planes: Planes) -> Option<(GFlow, Layer)> {
`.unwrap()` here are for dirty development assertions. I personally don't want to make the function complex just for gracefully handing them. I understand these lines must be swept away soon...

2025-04-24 18:58 UTC, EarlMilktea commented on src/internal/validate.rs
> +                let err = anyhow::Error::from(ExcessiveNonZeroLayer(u));
Merged in 2ae6999c6a9375ad9ebe562b0067926ee6075998 .

2025-04-24 22:10 UTC, EarlMilktea commented on python/fastflow/_common.py
> +        return type(err)(self.decode_errmsg(str(err)))
Updated. Could you take a look?

2025-04-24 22:10 UTC, EarlMilktea commented on src/common.rs
> +pub enum FlowValidationError {
Updated.

2025-04-24 22:13 UTC, EarlMilktea commented
@thierry-martinez Thoroughly refactored the error handling codes. Could you take a look?

MEMO: Will add tests later, provided the design itself is acceptable.

2025-04-25 17:00 UTC, thierry-martinez requested changes

2025-04-25 17:06 UTC, EarlMilktea commented on python/fastflow/_common.py
> +        return layer_
This is necessary because we need to verify that the key set is contiguous, or we couldn't `list[int]` as if it were `dict[int, int]` .

2025-04-25 17:16 UTC, EarlMilktea commented on src/gflow.rs
>  pub fn find(g: Graph, iset: Nodes, oset: Nodes, planes: Planes) -> Option<(GFlow, Layer)> {
Partly fixed in 08069183e4b87e073ec3cceab3244eb2b250aaa5 . `needless_pass_by_value` could not be removed (once I tried it by adding `&`) if I remember correctly.

2025-04-25 17:19 UTC, EarlMilktea commented on src/gflow.rs
>  pub fn find(g: Graph, iset: Nodes, oset: Nodes, planes: Planes) -> Option<(GFlow, Layer)> {
Oops I was replying to wrong comments. Let me remove them.

2025-04-26 22:40 UTC, thierry-martinez commented on python/fastflow/_common.py
> +        return layer_
I don't understand the problem: as you noted it, the "key set" of `list[int]` is contiguous by definition, and if `layer[v]` is missing for some `i`, then `layer[v]` will raise an exception.

2025-04-26 23:43 UTC, EarlMilktea commented on python/fastflow/_common.py
> +        return layer_
Oops, you're right...

2025-04-29 04:54 UTC, EarlMilktea commented on src/gflow.rs
>  pub fn find(g: Graph, iset: Nodes, oset: Nodes, planes: Planes) -> Option<(GFlow, Layer)> {
@thierry-martinez Reminder

2025-05-05 06:25 UTC, EarlMilktea commented
@thierry-martinez Could you review again?

2025-05-13 16:42 UTC, shinich1 commented
note (cc @EarlMilktea ): to be merged in 18 hrs if no follow-up comments by @thierry-martinez by then.

2025-05-14 06:33 UTC, thierry-martinez approved these changes
LGTM! Sorry for the long delay. Thanks for this work!

2025-05-14 08:12 UTC, merged